### ISSUE TITLE
Rider apparently creating superfluous .meta files

### ISSUE THREAD

**Issue by Kylotan** [JetBrains/resharper-unity#1481]
Since a recent upgrade, I've found that sometimes I am getting a bunch of meta files created for files outside the Assets directory and that should not have meta files. These are mostly for csproj files. I just have to keep deleting them.

I can't 100% verify that it is Rider and not Unity causing this, but:

1. It's only happening to me on this project - everyone else uses Visual Studio
2. It only happens when Rider is in focus, and when it's active - I believe I saw it say "synchronising project" at the bottom, before flashing up the 'do you want to add this to Git?' dialog

It's probably worth noting that our repository contains both standard Unity projects and a packages directory, and maybe this is confusing Rider and making it think the root is further up than normal.

**Comment by van800** [comment]
@Kylotan What is your Rider version and Unity version? When this issue happens again, please list here paths of those meta files. A screenshot may help.
I tried to reproduce, but no, it doesn't happen.
Feel free to reopen the issue.

**Comment by Kylotan** [comment]
Sorry, should have remembered those details.

- Unity 2019.2.1f1
- Rider 2019.3.1

Can't share full paths due to client confidentiality but here are some examples of meta files that appeared in the directory that contains Assets.
![image](https://user-images.githubusercontent.com/1117104/72430574-a5820e80-378a-11ea-8152-23a9c4dd4148.png)

**Comment by Nezz** [comment]
Our team is experiencing the same issue. It happens on both Windows and macOS. Worst of all, the Rider plugin even causes the meta files to get created outside the folder of the repository.

Example folder structure:
- MyRepo
  - RepoFile.json
  - UnityProject
    - MyCode.csproj
    - Assets
      - Actual files that should have meta files

Meta files get created for:
1. MyRepo
2. RepoFile.json
3. MyCode.csproj

Versions:
JetBrains Rider 2019.3.1
Build #RD-193.5662.14, built on December 19, 2019
Unity 2018.4.15f1

**Comment by van800** [comment]
@Nezz Do you have a separate sln on the top level?

**Comment by van800** [comment]
cherry-pick to 2019.3.2 https://github.com/JetBrains/resharper-unity/pull/1491

**Comment by Kylotan** [comment]
Thanks for the rapid fix! But, is there any workaround in the meantime? This is making it very hard to work with a Unity project and version control when it keeps making extra meta files everywhere, including in submodules.

**Comment by van800** [comment]
@Kylotan 
You may set some special gitignore rules.
You may use one of the older builds https://www.jetbrains.com/rider/download/other.html
However 2019.3.2 is planned to be released at the end of next week.

**Comment by van800** [comment]
Sorry for delay. 2019.3.2 with this fix was released.

**Comment by bartlomiej-dawidow** [comment]
Confirmed, the issue is gone on my end. Note that after updating Rider you have to restart Unity, I guess that otherwise the plugin doesn't reload.

**Comment by bartlomiej-dawidow** [comment]
OK that was premature, it worked once but failed the next time when unshelving a a patch with moved .metas:
<img width="636" alt="Screen Shot 2020-02-13 at 23 57 39" src="https://user-images.githubusercontent.com/9422443/74486361-136e4280-4ebd-11ea-8b1b-6ad37e6a593f.png">

**Comment by bartlomiej-dawidow** [comment]
My workaround is handpicking .meta files and unshelving them first, and then unshelving everything else.

**Comment by bartlomiej-dawidow** [comment]
@van800 This is just to let you know that we are still seeing the error in Rider 2019.3.4.

**Comment by van800** [comment]
@bartlomiej-dawidow Thank you for the heads-up, somehow I missed your previous comments. It seems that you are facing some issue different from originally reported. This issue and its fix are all about `.meta` files outside Assets folder. It you have some different issue, please report it separately. I would be happy to investigate.

**Comment by bartlomiej-dawidow** [comment]
@van800 Sure: #1579
