### ISSUE TITLE
Warning shown in Rider: "Advanced Unity Integration is Unavailable"

### ISSUE THREAD

**Issue by snappedToGrid** [JetBrains/resharper-unity#2366]
The full error I'm getting is:

"Advanced Unity Integration is Unavailable

Make sure "JetBrains Rider Editor" is installed in Unity’s Package Manager and Rider 2022.2.3 is set as the External Editor."

Despite installing the JetBrain Rider Editor, setting it as the External Script Editor in Unity, regenerating project files, and restarting both Unity and Rider multiple times to no avail.

![image](https://user-images.githubusercontent.com/94614297/196979822-994f8f33-137e-4750-b94e-a862c35040e7.png)
![image](https://user-images.githubusercontent.com/94614297/196979897-d9e07b18-bf58-4aab-a3a8-e41930c27d87.png)
![image](https://user-images.githubusercontent.com/94614297/196980006-c491332c-625b-44ae-9c50-3a111dfcef79.png)

Any help is greatly appreciated.

Thanks.

**Comment by van800** [comment]
Is anything else not working, except of the notification being shown? Like pressing Play in Rider should put unity editor to play mode.

**Comment by snappedToGrid** [comment]
Everything else seems to be fine.

**Comment by van800** [comment]
Could you please add steps-to-reproduce?
The only one way to reproduce this, which I know, is when file `Library/EditorInstance.json` exists, but Unity is not running. Such case may happen, when Unity process was killed or if this file is committed to the vcs.

**Comment by AndrewNovakP** [comment]
Unity 2022.2.0, Rider 2022.3, Rider editor package 3.0.17

Same issue. Also, solution Analysis Info is broken and does not recognize SerializeField, MonoBehaviour, bool, etc
![image](https://user-images.githubusercontent.com/6072592/207514343-e8142243-7d45-4ef8-8f1b-60c90b5728d5.png)

**Comment by van800** [comment]
@AndrewNovakP would you please submit an issue with Help - Report a Bug, agree to attach logs.
I think the problem might more likely be with project generation rather than analysis.

**Comment by AndrewNovakP** [comment]
Thanks for the reply @van800 
After build (build-build solution) in rider I has some errors
![image](https://user-images.githubusercontent.com/6072592/207618459-c62cc83b-878d-4839-93cf-30f596cec360.png)
![image](https://user-images.githubusercontent.com/6072592/207618587-cd239fec-23e5-4ed2-8424-4674159682fd.png)

After that I tried to select MSBuild version: C:\Program Files\dotnet\sdk\6.0.404\MSBuild.dll and voila - build is succeeded without errors in the right bot corner

**Comment by attilam** [comment]
Setting MSBuild version manually to another SDK fixed it for me as well!

Rider 2022.3.2, Unity 2021.3.16.f1, Rider package 3.0.18

**Comment by Snaki94** [comment]
same story, unity 2022.3.7f1 Rider 2023.2 and package 3.0.24
![image](https://github.com/JetBrains/resharper-unity/assets/19492464/c56b8eb7-20ef-4f46-884e-6c39e79d696a)
![image](https://github.com/JetBrains/resharper-unity/assets/19492464/c62a6fe7-0cc2-4cb9-8468-d63a89ce2594)
![image](https://github.com/JetBrains/resharper-unity/assets/19492464/b302afa0-d055-4d7a-806d-8c0963bde4ff)

**Comment by van800** [comment]
@Snaki94 Could you try to change MSBuild in Rider settings to another one if any in File | Settings | Build, Execution, Deployment | Toolset and Build. It has already helped others.

**Comment by tosiabunio** [comment]
The same here, the same versions as above, changing MSBuild version doesn't help.

**Comment by Snaki94** [comment]
Disabled Resharper build and MSBuild 14.0 seems to have helped me

**Comment by van800** [comment]
Github doesn't allow private attachments, so it might be uncomfortable to attach the logs directly here.
Can I ask to attach those to this issue https://youtrack.jetbrains.com/issue/RIDER-97921?

**Comment by van800** [comment]
Sorry for the inconvenience. I have just verified that this was fixed in the todays nightly build of Rider 2023.2. Nightly builds are available in the JetBrains Toolbox App.

**Comment by CodeSuperHero** [comment]
@van800  rider version 2023.2 , unity version 2022.3.9f1, JetBrains Rider Editor 3.0.25， 
i tried set msbuild to .net sdk, jetbrains 2023.1 amd64 msbuid, dont resolve.
now, i cant press F12 to see unity api define,  dont use "connect to unity editor" "start unity "yet

**Comment by van800** [comment]
@CodeSuperHero Please use nightly build of Rider 2023.2, available in JetBrains Toolbox app. The fix would also appear in the upcoming 2023.2.2.

**Comment by nitinraj4** [comment]
@van800 I'm still getting the message "Advanced Unity integration is unavailable message" in  2023.2.3, It shows connected to Unity but the message doesn't go away.

**Comment by van800** [comment]
@nitinraj4 the popup should get closed, but notifications do not disappear from the Notifications toolwindow, which is expected. What exactly do you see?
