### ISSUE TITLE
breakpoint can not work

### ISSUE THREAD

**Issue by Zhuangdum** [JetBrains/resharper-unity#262]
it seems i have attached to the unity, but the break point still has no response; i have try to reintall my rider and unity, but i just doesn‘t help

console msg: Input/Output redirection disabled: Debugger is attached to an already running process
but debug output windows output nothing

**Comment by van800** [comment]
Please attach zip and attach logs from Help->Show log in Files.

**Comment by Zhuangdum** [comment]
[Rider2017.2.zip](https://github.com/JetBrains/resharper-unity/files/1443220/Rider2017.2.zip)

it's my rider log zip, and two screenshot when i try to attach to unity process, thank you!

**Comment by IvanPashchenko** [comment]
@Zhuangdum This should be fixed in Rider 2017.2.1. Could you please check whether the fix worked for you?

**Comment by citizenmatt** [comment]
Closing due to inactivity. Please reopen if it hasn't solved the issue.

**Comment by ThatFatPat** [comment]
Still Have this on 2017.3

**Comment by mvedie** [comment]
Same probleme, anyone have found a solution ?

**Comment by MohsenneChaverdie** [comment]
2017.3.1.: having the same issue.

**Comment by van800** [comment]
Could anyone please post all logs from Help->Show log in Files, including "Debugger Worker" folder? Just everything except "threadDumps*"

**Comment by MohsenneChaverdie** [comment]
@van800
[log.zip](https://github.com/JetBrains/resharper-unity/files/1711675/log.zip)
Mono runtime version: 2.0.50727.1433

**Comment by ArsenyChernyaev** [comment]
@MohsenneChaverdie Hi! Could you please provide me with more details? What is your working scenario? According to logs your breakpoint is bound to correct location right after assembly load

**Comment by MohsenneChaverdie** [comment]
I tested it again, and now mysteriously it is breaking at the break point correctly. The time that I tested it, Rider was not reacting to the breakpoint at all. Next time that happens, I will record a video of it. Thanks for such a good support.

**Comment by van800** [comment]
@ThatFatPat @mvedie does it still reproduce for you in Rider 2017.3.1?

**Comment by van800** [comment]
Closed due to inactivity, I guess fixed in Rider 2018.1

**Comment by atlemael** [comment]
I'm also seeing this issue in 2018.1.1, attached clean log from an empty project with 1 script and a couple of breakpoints added here:

https://gist.github.com/atlemael/3634aa37b8dee0e0c9a477be324b2bf6

**Comment by van800** [comment]
@atlemael Debug related logs are in "Debugger Worker" folder, please attach it.

**Comment by atlemael** [comment]
https://www.dropbox.com/s/oxtu6teyqz63gst/DebuggerWorker.zip?dl=0

**Comment by danielbrauer** [comment]
I was getting the same error in 2018.1.1 while debugging a Unity project in a trunk version of Unity. Upon upgrading to 2018.1.2, I get a slightly more verbose error:
<img width="1683" alt="screenshot 2018-06-06 14 53 55" src="https://user-images.githubusercontent.com/5722430/41042519-2827e066-69a2-11e8-8d14-4c7ec8a8dd56.png">
Here are my logs:
[2018.1.2 Logs.zip](https://github.com/JetBrains/resharper-unity/files/2076546/2018.1.2.Logs.zip)

**Comment by danielbrauer** [comment]
I was getting the same error in 2018.1.1 using a recent trunk version of Unity. Switching to 2018.1.2 I get a more verbose error:
<img width="1683" alt="screenshot 2018-06-06 14 53 55" src="https://user-images.githubusercontent.com/5722430/41042661-826e0aa0-69a2-11e8-87a9-2f95ee432bde.png">
Here are my logs:
[2018.1.2 Logs.zip](https://github.com/JetBrains/resharper-unity/files/2076550/2018.1.2.Logs.zip)

**Comment by capyvara** [comment]
From times to times I have the same error as @danielbrauer 

I've been able to "fix" it by disabling Rider plugin, settings Visual Studio as the editor, relaunching everything, letting Unity generate the unmodified projects for VS, attach the debug once.

Then back to Rider as the default editor, re-enable plugin and relaunch everything and breakpoints start to work.

**Comment by hugoBourretDesmarais** [comment]
I have the same error and I can't fix it. I'm now using VSCode instead.
![screen shot 2018-07-31 at 9 55 18 am](https://user-images.githubusercontent.com/25404215/43463966-e4b1f98a-94a7-11e8-9520-61ba6c90ae32.png)

**Comment by ArsenyChernyaev** [comment]
@hugoBourretDesmarais Please attach DebuggerWorker logs of last unsuccessful run here

**Comment by IvanPashchenko** [comment]
https://rider-support.jetbrains.com/hc/en-us/articles/360001079770-How-to-collect-Rider-logs-
^ In logs folder there will a DebuggerWorker folder, that's the logs that we need to diagnose this issue

**Comment by ArsenyChernyaev** [comment]
@hugoBourretDesmarais Is it possible to provide us with sample solution?

**Comment by candycat1992** [comment]
I had the same problem. Close all unity projects and restart solved my problem.

**Comment by ryo0ka** [comment]
Having the same problem, can't fix it with any solutions above.

Log:
[JetBrains.Debugger.Worker_2018-08-20__01-16-23.log](https://github.com/JetBrains/resharper-unity/files/2301640/JetBrains.Debugger.Worker_2018-08-20__01-16-23.log)

Sample project: 
[Debugger Sample Project.zip](https://github.com/JetBrains/resharper-unity/files/2301682/Debugger.Sample.Project.zip)

Reproduction process:
1. Open Unity Editor
2. Open Rider via the editor
3. Wait until initialized
4. Start debugger

**Comment by van800** [comment]
@ryo0ka Have you tried Rider 2018.2 RC/Nightly builds?

**Comment by hodor** [comment]
I'm also having this issue, started right after updating to 2018.2.
None of the solutions above seems to work for me. Here are my logs:
[2018.2_macos.zip](https://github.com/JetBrains/resharper-unity/files/2315822/2018.2_macos.zip)

**Comment by van800** [comment]
@hodor Does it reproduce on any project or just yours? What are your steps? Thanks!

**Comment by hodor** [comment]
@van800 I just tried on another project and got the same issue:
```
Input/Output redirection disabled: Debugger is attached to an already running process
"/Applications/Rider 2018.2.app/Contents/lib/ReSharperHost/runtime.sh" "/Applications/Rider 2018.2.app/Contents/lib/ReSharperHost/JetBrains.Debugger.Worker.exe" --mode=client --frontend-port=59152
```
I opened the project and created a new cs file in the assets folder. I double clicked the .cs file to open the source on Rider. I tried adding a breakpoint anywhere in the code and got the same problem.

**Comment by ArsenyChernyaev** [comment]
@hodor It's normal output for debugger console tab. Have you attached your script to some game object?

**Comment by hodor** [comment]
@ArsenyChernyaev I'm working mostly on Editor scripts now. Besides that output, all my breakpoints are replaced by a grey stop icon with the error: `Not found loaded method for (...)`

**Comment by van800** [comment]
Have you tried anything like the following
```
  [InitializeOnLoad]
  public static class PluginEntryPoint
  {
    static PluginEntryPoint()
    {
     Debug.Log("something");
}}
```

**Comment by hodor** [comment]
Yes, on the project I was working on sometimes it does work even though the breakpoints are all disabled and showing errors. But sometimes it also takes a long time for the code to break. Other times the breakpoint merely is disabled, and it the execution never stops.

I'll try on a new project and will let you know.

**Comment by hodor** [comment]
On a brand new project, the breakpoints are still greyed out by default and always with the same error. 
I setup Editor and Runtime breakpoints. After running the project, the execution started to break with no delay on the right line.
I closed Rider and reopened my original project trough Unity. At first, the breakpoints were still disabled, but it started to break at the right time.

Everything seems to work now, even on my problematic project but I have no idea what actually fixed the problem :)

**Comment by IlyaBokovenko** [comment]
Had the same issue and fixed it. In my case problem appeared when I start project from mounted drive (via subst). Solved by starting project by full path (via Unity Hub) and cleaning csproj/sln files and obj, Temp, Library\ScriptAssemblies folders

Windows 10, Unity 2018.2.13f1, Rider 2018.3.1

**Comment by silverua** [comment]
I was getting this issue with skipping breakpoints in my Unity project with Untiy 2018.3.0f2 and Rider 2018.2. Rider and the project were installed on different hard drives.

Updated to Rider 2018.3 today, tried it on different hard drives, just like in the previous setup. The issue was not fixed, but I started getting grayed out breakpoints when I attach the debugger and warnings of type "Not found loaded method for" (as posted above by @danielbrauer for example)

Tried re-installing Rider on the same hard drive where the project is. Still getting the same warnings and breakpoints not triggering. Deleting the csproj/sln files and obj, Temp, Library\ScriptAssemblies folders did not help. Installed Unity Hub. Not sure if I understand what is meant by "starting project by full path", but just opening the project from Unity Hub did not change anything. 

Would appreciate any help with this.

**Comment by anthrich** [comment]
![image](https://user-images.githubusercontent.com/4399568/52179490-3a3a6900-27d3-11e9-905e-5fd036a70142.png)

Same problem. 2 things have changed in my project around the time this started happening:

- I started adding Mirror networking attributes to some Components
- I added a symlink on the Assets folder to run two instances of the project in Unity

**Comment by van800** [comment]
@anthrich symlink reportedly brakes debugging.

**Comment by anthrich** [comment]
Strange - after the revert, the symlink is still in place but debugging is working again. I'll see if I can pin it down any further.

**Comment by van800** [comment]
Dear Devs! In case issue fires again, please create an issue in https://youtrack.jetbrains.com/issues/RIDER
and follow up here with a link.
Debugging is Rider core functionality it has to be processed and planned in YT.
Thank you!

**Comment by BassaForte** [comment]
Still having this issue with Unity 2018.3.6f1, Rider 2018.3.3.

Will not attach to any breakpoints in my project. I first got the issue on Unity 2019.2 alpha, and downgraded to 2019.1 beta, thinking the alpha just wasn't supported. Still got the issue, so downgraded again to my current preferred version 2018.3.6f1, and still getting the issue.

I've deleted the Library, obj, all .sln / .csproj files in my project each time while downgrading, to no avail.

I'm also sure I'm using the most recent version of the plugin (at least, Rider tells me so).

**Comment by doctorpangloss** [comment]
This is still happening.

**Comment by van800** [comment]
@doctorpangloss Issues with debugger are out of this plugin scope, please report then in https://youtrack.jetbrains.com/issues/RIDER. Thank you!

**Comment by jonyzhao** [comment]
Still happening in Rider 2021.2.1 + Unity2018.4.11

**Comment by citizenmatt** [comment]
@jonyzhao Could you use the Help -> Report a Bug action to report an issue with logs that show the breakpoints not working, please?

As mentioned previously in this topic, breakpoints will look like they're inactive until the code is loaded by Unity/Mono and used. At this point, the breakpoint should resolve and activate.

Also make sure that breakpoints haven't been muted. There's a toggle button in the debug tool window to mute - if active, all breakpoints are shown as grey and won't be hit. Use the toggle button to activate them again.
