### ISSUE TITLE
Supported C# level is incorrect with .NET 3.5

### ISSUE THREAD

**Issue by Nezz** [JetBrains/resharper-unity#528]
The supported C# level with .NET 3.5 is currently always set to 4 by the `CsprojAssetPostprocessor`:
>// Unity 5.5+ supports C# 6, but only when targeting .NET 4.6. The enum doesn't exist pre Unity 5.5
https://github.com/JetBrains/resharper-unity/blob/master/unity/JetBrains.Rider.Unity.Editor/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs#L406

However, Unity actually supports C# 6 even with .NET 3.5. For example this compiles without a problem:
<img width="271" alt="screen shot 2018-04-19 at 13 36 45" src="https://user-images.githubusercontent.com/431167/38987023-0f51f018-43d7-11e8-8c89-31920818c95e.png">

<img width="397" alt="screen shot 2018-04-19 at 13 36 38" src="https://user-images.githubusercontent.com/431167/38987022-0f32387c-43d7-11e8-8aa7-443a4a95bd7e.png">

But it fails in Rider:
<img width="1040" alt="screen shot 2018-04-19 at 13 39 41" src="https://user-images.githubusercontent.com/431167/38987056-24244932-43d7-11e8-891d-fa5a6760ac81.png">

I have tested this with Unity 2017.2. I don't know exactly when they switched to the new compiler that always supports C# 6.0.

**Comment by van800** [comment]
Please use Unity Rider preferences to override TargetFrameworkVersion
![image](https://user-images.githubusercontent.com/1482681/38987650-cdb381b8-43d0-11e8-8984-03c49869f717.png)

**Comment by van800** [comment]
Ah sorry, it seems I have got the question wrong. It is more about LangVersion.

**Comment by van800** [comment]
What is your Rider version?
In Rider 2018.1 we are not changing LangVersion if Unity have set some bigger value.
So there should be not problem.
Please try it https://www.jetbrains.com/rider/eap/

**Comment by Nezz** [comment]
Unity sets it to 4 which is also incorrect:
`<LangVersion>4</LangVersion>`

**Comment by Nezz** [comment]
I submitted a bug report to Unity (#486239), but it would be probably best to set this from Rider as it might have to with MonoDevelop compatibility.

**Comment by van800** [comment]
Ok, I will add a setting to override LangVersion. Will it be enough?

**Comment by Nezz** [comment]
Perfect :)

**Comment by van800** [comment]
Should appear in the nightly builds in a couple of days. Available via https://www.jetbrains.com/toolbox/app/

**Comment by Nezz** [comment]
I have received an update from Unity's QA team:
>The mono C# compiler does not strictly enforce some langversion features. Given that we are migrating to a newer version of mono (and Roslyn) we won't be fixing this issue.

**Comment by van800** [comment]
Thanks for update. Is there anything I can improve about the case?

**Comment by Nezz** [comment]
I think having an override for `TargetFrameworkVersion` is perfectly fine. Is it already in 2018.1.1 EAP?

**Comment by van800** [comment]
No. It is in the nightly builds. Nightly builds are available via https://www.jetbrains.com/toolbox/app/

**Comment by Nezz** [comment]
Can we expect it to be part of 2018.1.1?

**Comment by van800** [comment]
Everything from current nightly builds will be in 2018.1.1 RTM

**Comment by van800** [comment]
@Ethan-VisualVocal Thanks for the heads up, I confirm there is a problem.

**Comment by van800** [comment]
Immediate workaround would be adding [this script](https://gist.github.com/van800/875ce55eaf88d65b105d010d7b38a8d4) 
to Editor folder. @Ethan-VisualVocal 
It would require some testing to justify adding it to our Editor Plugin assembly itself.

**Comment by Nezz** [comment]
To be honest, it's currently rather annoying that the order of postprocessors cannot be modified. In our project we have a post processor that changes the language level to `6` but then Rider's post processor changes it back to `4`.

**Comment by van800** [comment]
@Nezz In the latest Nightly I have fixed a bug, which was braking logic to avoid decreasing LangVersion.
So the best option is to grad a recent nightly. It differs very little with release 2018.1.1.
If you don't want Nightly there are still options. You may Override LangVersion in settings
![image](https://user-images.githubusercontent.com/1482681/40589596-386a7de4-61f0-11e8-9a00-4f083f034e37.png)
Or play with your script post processing order
https://github.com/JetBrains/resharper-unity/blob/wave12/unity/JetBrains.Rider.Unity.Editor/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs#L20

**Comment by Nezz** [comment]
@van800 `GetPostprocessOrder` is not used in case of `OnGeneratedCSProjectFiles`. See Unity source code here:
https://github.com/Unity-Technologies/UnityCsReference/blob/3cfc6c4729d5cacedf67a38df5de1bfffb5994a3/Editor/Mono/AssetPostprocessor.cs#L101

It's only taken into account in case of regular asset post processors:
https://github.com/Unity-Technologies/UnityCsReference/blob/3cfc6c4729d5cacedf67a38df5de1bfffb5994a3/Editor/Mono/AssetPostprocessor.cs#L215

**Comment by van800** [comment]
@Nezz Ah, thank you, it is good to know. Let me know, how Nightly Build worked for you.

**Comment by citizenmatt** [comment]
Note that this is still an issue with the incremental compiler 0.0.42-preview.14. It will set the language version to "7" rather than 7.2, and doesn't check the value before writing.

**Comment by flamz3d** [comment]
fixed in 0.0.42-preview.16
