### ISSUE TITLE
Cannot run GameObject tests from ReSharper/Rider

### ISSUE THREAD

**Issue by BioTiNe** [JetBrains/resharper-unity#96]
When using anything inside the unity engine namespace when running unit tests in Resharper the exception "System.Security.SecurityException : ECall methods must be packaged into a system module" is thrown, for example:
```
using NUnit.Framework;
using UnityEngine;

[TestFixture]
public class ExampleTest
{
    [Test]
    public void UnityEngine_NewGameObject()
    {
        var newGameObject = new GameObject(); // Throws the exception
    }
}
```

**Comment by citizenmatt** [comment]
Rider's test runner can only run tests that don't use the editor API, because Rider runs tests in an external process, rather than in the Editor instance. I don't believe there is a way around this - tests run in other runners, such as Visual Studio and MonoDevelop have the same issue.

@CapnRat is there any way for Rider to handle this, or do the tests have to run directly in the editor process?

**Comment by CapnRat** [comment]
Correct, the assemblies have a dependency on the native application. Much of the API in the Unity assemblies are ICalls into our native engine, which needs to be initialized and running before calling them.

If you really want to have the tests running inside of Rider/Resharper/MonoDevelop, I imagine it would be possible for your test framework to invoke Unity's [Editor Test Runner](https://docs.unity3d.com/Manual/testing-editortestsrunner.html) via command line.

**Comment by aaronjbaptiste** [comment]
Some more details are described here: https://github.com/JetBrains/Unity3dRider/issues/45

**Comment by igisav** [comment]
Is this not the purpose of Rider to mock the missing library of Unity?

**Comment by citizenmatt** [comment]
No. This isn't a missing library, it's Unity's core API, large parts of which are written in native code, rather than .NET code. It's not possible to mock this API without reimplementing all of UnityEngine.dll, which just isn't feasible.

If a test makes use of any of Unity's core (natively implemented) API, it has to run in the Unity Editor instance. There's no way around this. But if the test is just plain .NET, you can run the tests in Rider.

The ideal solution, that we're working towards, is that Rider will automatically run or debug in the Editor instance directly from the standard Rider testing UI.

**Comment by hgonzalez94** [comment]
When I try running my tests I get this error from rider:

![image](https://user-images.githubusercontent.com/6015420/27937767-609666ca-626e-11e7-8eb2-9a000dcd43d7.png)

This is how my tests look:
![image](https://user-images.githubusercontent.com/6015420/27937778-781a1990-626e-11e7-8ea8-5d9076c55e48.png)

I'm using:

Rider 2017.1 EAP
Build #RS-171.4456.902, built on June 29, 2017
Rider EAP User
Expiration date: July 29, 2017
JRE: 1.8.0_112-release-736-b17 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

Thoughts @citizenmatt ?

**Comment by citizenmatt** [comment]
Are you using any NUnit addins in your source? This looks like two things are both trying to use Mono.Cecil, and one of them is getting a version it doesn't expect, and there's a method (property) that's not implemented. Do the tests work correctly when you run them from inside the Unity Editor? If the tests rely on Editor functionality, then Rider can't run them.

**Comment by hgonzalez94** [comment]
Yeah they do run in the unity test runner. I don't think I'm using NUnit addins, I just added the unit tests from an old project I had with an A* path finding framework. I'll have to take a closer look because off the top of my head I can't think of anything that could be using NUnit.

**Comment by aaronjbaptiste** [comment]
I have the same error as  @hgonzalez94

**Comment by van800** [comment]
I am closing issue here, because it is for sure issue in Rider itself, please vote:
https://youtrack.jetbrains.com/issue/RIDER-6711

**Comment by AndreyAkinshin** [comment]
The "System.MissingMethodException: Method 'Mono.Cecil.TypeDefinition.get_Interfaces' not found." problem will be fixed in Rider 2017.3.1 RTM.

**Comment by citizenmatt** [comment]
Rider 2018.1 will now run Unity tests in the Unity editor process, so it should fix the initial problem (ECall errors)

**Comment by Baccanno** [comment]
Great news!
Will this also work on resharper ?

**Comment by citizenmatt** [comment]
Short answer is no, at least not yet. It requires the Unity editor plugin we've written for Rider, but we haven't even investigated how much work it is to port that to ReSharper. The plugin makes a bunch of assumptions that it's talking to Rider, not the least of which is the protocol used to communicate between Rider and the Unity editor. But we'll take a look.

**Comment by bit-man** [comment]
Still having the same issue 

```
System.MissingMethodException : Attempted to access a missing method.
  at (wrapper managed-to-native) UnityEngine.GameObject:Internal_CreateGameObject (UnityEngine.GameObject,string)
  at UnityEngine.GameObject..ctor () [0x00007] in <8d32f887d20f494ebb751c6ec804b63d>:0 
  at Tests.ExampleTest.UnityEngine_NewGameObject () [0x00001] in /Users/xxxxxxxx/ExampleTest.cs:12 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
```

I'm using Rider on Mac :

JetBrains Rider 2018.1 EAP
Build #RD-181.4379.788, built on April 6, 2018
Rider EAP User
Expiration date: May 6, 2018
JRE: 1.8.0_152-release-1136-b23 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

**Comment by van800** [comment]
@bit-man Unity version? Thanks!

**Comment by van800** [comment]
@bit-man could you please try the latest nightly build via https://www.jetbrains.com/toolbox/app/
I checked on mac right now (with 2017.3.1f1) - it just works.

**Comment by bit-man** [comment]
It worked.
Thanks!

**Comment by hggz** [comment]
blessed be!! <3 <3 🙏🔥🍆😩💯
